#!/bin/bash
# This hook is sourced after a new virtualenv is activated.

pip install pdbpp remote-pdb

# install requirements if present
if [[ $(find . -maxdepth 1 -name "requirements.txt") ]]; then
  pip install -r requirements.txt
fi

# create pyright config for the new virtualenv
venv_name="$(basename "$VIRTUAL_ENV")"
virtualenv_dir="$(dirname "$VIRTUAL_ENV")"
echo "{ \"venvPath\": \"${virtualenv_dir}\", \"venv\": \"${venv_name}\" }" > pyrightconfig.json
