#!/bin/bash
# This hook is sourced after a new virtualenv is activated.

pip install pdbpp remote-pdb

# ensure we create a requirements file, install the packages and delete it
# 1. For work
if [[ $(find . -maxdepth 1 -name "poetry") && $(uname -s) == "Darwin" ]]; then
  ./poetry install
# 2. For personal projects that use poetry
elif [[ $(find . -maxdepth 1 -name "poetry.lock") ]]; then
  poetry export --with dev --output requirements.txt
  pip install -r requirements.txt
  rm requirements.txt
# 3. For other projects that use a requirements.txt file only
elif [[ $(find . -maxdepth 1 -name "requirements.txt") ]]; then
  pip install -r requirements.txt
fi

# create pyright config for the new virtualenv
venv_name="$(basename "$VIRTUAL_ENV")"
virtualenv_dir="$(dirname "$VIRTUAL_ENV")"
echo "{ \"venvPath\": \"${virtualenv_dir}\", \"venv\": \"${venv_name}\" }" > pyrightconfig.json
