# Allows you to save tmux sessions even after reboots
# Save    ->  Ctrl-b + Ctrl-s
# Restore ->  Ctrl-b + Ctrl-r

# PLUGINS
# prefix + I to install
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# allow vim sessions to be saved
set -g @resurrect-strategy-vim 'session'

# allows one to scroll
setw -g mouse on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
