# Allows you to save tmux sessions even after reboots
# Save    ->  Ctrl-b + Ctrl-s
# Restore ->  Ctrl-b + Ctrl-r

run-shell ~/bin/tmux-resurrect/resurrect.tmux
# for vim;
set -g @resurrect-strategy-vim 'session'


setw -g mouse on
