"""" FUNCTIONS """""""""""""""""""""""""""""""""""
let g:vimrc = resolve(expand('<sfile>:p'))
let g:vimdir = fnamemodify(vimrc, ':h')

function! Source(f)
  exec 'source ' . g:vimdir . '/' . a:f
endfunction

" not sure what this does but is required for tab completion
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

"""" PLUGINS """"""""""""""""""""""""""""""""""""""""
call plug#begin()

call Source('base.vim')

" TAG BROWSER: get class/function names in a sidebar
Plug 'majutsushi/tagbar', {'on': 'TagbarToggle'}

" GUTENTAGS: automatic tag generation
Plug 'ludovicchabant/vim-gutentags'

" LINTER: syntax checkers
Plug 'w0rp/ale'

" HIGHLIGHTING: syntax highlighters for non-python languages
Plug 'sheerun/vim-polyglot'

" FILES: explore dirs in another buffer
Plug 'scrooloose/nerdtree', { 'on': ['NERDTreeFind', 'NERDTreeToggle'] }
Plug 'Xuyuanp/nerdtree-git-plugin', { 'on': ['NERDTreeFind', 'NERDTreeToggle']}

" GIT: use git commands in vim e.g. Gblame
Plug 'tpope/vim-fugitive'
Plug 'jlfwong/vim-mercenary'

" MARKDOWN: preview markdown files
Plug 'JamshedVesuna/vim-markdown-preview', { 'for': 'markdown' }

"OUTPUT: execute commands in a new buffer
Plug 'vim-scripts/RunView'

"HIGHLIGHTING: highlights regex changes during typing
Plug 'markonm/traces.vim'

" COLORSCHEMES: various colorschemes. copy all schemes to ~/.vim/colors
Plug 'morhetz/gruvbox'
Plug 'pbrisbin/vim-colors-off'
Plug 'reedes/vim-colors-pencil'

"EXTENDED FUNCTION: further improve editing
Plug 'tpope/vim-surround'

" CSV: manipulate CSV files easily (READ THE DOCS)
Plug 'chrisbra/csv.vim', { 'for': 'csv' }

" HTML: automates HTML tags (check tutorial)
Plug 'mattn/emmet-vim', { 'for': ['javascript', 'html', 'css'] }

" STATUSLINE: lightweight status line
Plug 'itchyny/lightline.vim'
Plug 'maximbaz/lightline-ale'

" FILEFINDER: fuzzy file finder
" needs to be installed locally too
Plug '~/.fzf'
Plug 'junegunn/fzf.vim'

" TAB RENAMING: allows one to rename vim tabs and sustain them over sessions
Plug 'gcmt/taboo.vim'

" PERSONAL: my plugins
Plug 'superDross/class-builder'
Plug 'superDross/motion-plus'

call plug#end()

colorscheme gruvbox

"""" CHEATSHEETS """""""""""""""""""""""""""""""""""""""""""""""""""""""
function! KeyCheat()
  echo 'KEY BINDINGS'
  echo '    F2             = paste toggle'
  echo '    F3             = ALEFix'
  echo '    F4             = NERDTreeToggle'
  echo '    \-F4           = NERDTreeFind'
  echo '    F5             = view this cheatsheet'
  echo '    F6             = source .vimrc'
  echo '    F8             = tag bar'
  echo '    F9             = toggle highlight search'
  echo '    F12            = RunView'
  echo 'ALE'
  echo '    \-h            = ALEHover'
  echo '    \-r            = ALEFindReferenc'
  echo '    \-d            = ALEGoToDefinition'
  echo '    \-n            = ALEGoToDefinitionInTab'
  echo '    \-v            = ALEGoToDefinitionInVSplit'
  echo '    \-s            = ALEGoToDefinitionInSplit'
  echo '    \-j            = ALENext'
  echo '    \-k            = ALEPrevious'
  echo 'TAGS'
  echo '    C-]            = go to definition location'
  echo '    g-]            = give a list of all possible locations'
  echo '    C-t            = got to previous location'
  echo 'FZF'
  echo '    \-f            = fuzzy find file'
  echo '    \-a            = fuzzy grep using Ag'
  echo '    \-*            = fuzzy grep word under the cursor'
  echo '    C-v            = open fuzzy found file in a vs window'
  echo '    C-x            = open fuzzy found file in a sp window'
  echo '    C-t            = open fuzzy found file in a new tab window'
  echo 'SESSIONS'
  echo '   :mks t.vim      = create vim session'
  echo '   vim -S t.vim    = reopen vim session'
  echo 'TABS'
  echo '   \-Num           = go tab number'
  echo '   C-l             = go to next tab'
  echo '   C-h             = go to previous tab'
  echo '   :tabe f.txt     = open file in a new tab'
  echo '   TabooRename s   = rename current tab to s'
  echo 'GENERAL'
  echo '   \-t             = open small terminal'
  echo '   K               = show docs (python only)'
  echo '   C-w x           = swap column/row panes'
  echo '   C-w K           = move window to the topmost'
  echo '   C-w H           = move window to the bottomost'
  echo '   C-w N           = switch to vim mode in terminal'
endfunction

"""" CUSTOM KEY BINDINGS """"""""""""""""""""""""""""""""""""""
" function keys
nnoremap <F3> :ALEFix<CR>
nnoremap <F4> : NERDTreeToggle<CR>
nnoremap <leader><F4> :NERDTreeFind<CR>
noremap <F5> :call KeyCheat() <CR>
nnoremap <F8> :TagbarToggle<CR>
nnoremap <buffer> <F12> :exec extension_command<Bar>exec 'resize 40'<CR>

" Hovering
nnoremap <silent> <leader>h :ALEHover<CR>

" References
nnoremap <silent> <leader>r :ALEFindReferences<CR>

" Linting Jump
nnoremap <silent> <leader>j :ALENext<CR>
nnoremap <silent> <leader>k :ALEPrevious<CR>

" Jump to Definitions
nnoremap <silent> <Leader>d :ALEGoToDefinition<CR>
nnoremap <silent> <Leader>n :ALEGoToDefinitionInTab<CR>
nnoremap <silent> <Leader>v :ALEGoToDefinitionInVSplit<CR>
nnoremap <silent> <Leader>s :ALEGoToDefinitionInSplit<CR>

" Completion Bound to TAB
inoremap <silent> <expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ '<C-\><C-O>:ALEComplete<CR>'
inoremap <silent> <expr><S-TAB> pumvisible() ? "\<C-p>" : ""

" Go to newline when popup menu is active instead of selecting completion
inoremap <silent> <expr> <CR>
      \ pumvisible() ? "<CR><CR>" : "<CR>"

" auto close preview window when the popup menu is not visible
autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif

" fuzzy file/word finder key
nnoremap <leader>f :FZF<CR>
nnoremap <Leader>a :Ag<CR>
nnoremap <Leader>* :execute 'Ag' expand('<cword>')<CR>

"""" ALE """"""""""""""""""""""""""""""""""""""""""""""""
let g:ale_fixers = {
      \    '*': ['remove_trailing_lines', 'trim_whitespace'],
      \    'python': ['black', 'isort'],
      \    'sh': ['shfmt'],
      \    'javascript': ['eslint', 'prettier-eslint'],
      \    'json': ['jq'],
      \    'html': ['prettier'],
      \    'css': ['prettier', 'stylelint'],
      \    'markdown': ['prettier']
      \ }

" npm install typescript for completion to work in a local project
" Install:
"   python-language-server, tsserver, bash-language-server,
"   stylelint, csslint, jsonlint, mdl, vint, gitlint,
"   shellcheck
let g:ale_linters = {
      \   'javascript': ['flow', 'eslint', 'tsserver'],
      \   'python': ['pyls'],
      \ }

" completion settings
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 30
let g:ale_lint_delay = 0

" linter msg formatting
let g:ale_echo_msg_format = '%s [%linter%]'

" change signs
let g:ale_sign_error = '>>'
let g:ale_sign_warning = '--'


" hover docstrings
" set mouse=n
" set balloonevalterm
" let g:ale_set_balloons = 1

"""" FZF """""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" use ag instead of find, whcih is faster and repects .gitignore
let $FZF_DEFAULT_COMMAND = 'ag -g ""'
"""" GUTENTAGS """"""""""""""""""""""""""""""""""""""
let g:gutentags_ctags_exclude = ['node_modules', 'venv', '.git', '*.log', '.bundle', 'tmp', '*.pyc', '*.pyo']

"""" LIGHTLINE """"""""""""""""""""""""""""""""""""""""""""""""""""""""
" no longer show mode in bottom line
set noshowmode

let g:lightline#ale#indicator_warnings =  '⏶ '
let g:lightline#ale#indicator_errors = '✘ '

" show git branch in status line
let g:lightline = {
\ 'colorscheme': 'gruvbox',
\ 'active': {
\     'left': [ [ 'mode', 'paste'],
\               [ 'readonly',  'gitbranch', 'gutentags'],
\               ['filename', 'modified' ] ],
\     'right': [ [ 'lineinfo' ],
\                [ 'percent' ],
\                [ 'bufnum' ],
\                [ 'linter_errors', 'linter_warnings'] ]
\   },
\ 'component_function': {
\     'gitbranch': 'fugitive#head',
\     'gutentags': 'gutentags#statusline',
\   },
\ 'component_expand': {
\  'linter_warnings': 'lightline#ale#warnings',
\  'linter_errors': 'lightline#ale#errors',
\ },
\ 'component_type': {
\     'linter_warnings': 'warning',
\     'linter_errors': 'error',
\ },
\ }

"""" POLYGLOT """""""""""""""""""""""""""""""""""""""""""""""""""""""""
" work around for the PolyGlot GraphQL error in Javascript files
let g:polyglot_disabled = ['graphql', 'markdown']

"""" TABOO """""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" sustain tab names over sessions
set sessionoptions+=tabpages,globals
" naming format
let g:taboo_renamed_tab_format = ' %l %m '

"""" TAGBAR """""""""""""""""""""""""""""""""""""""""""""""""""""""""
" completely fold all classes/functions - except the one by the cursor
let g:tagbar_foldlevel = 0
let g:tagbar_compact = 1
let g:tagbar_autopreview = 1

"""" NERDTree """""""""""""""""""""""""""""""""""""""""""""
" refresh the file tree upon opening
function! NERDTreeRefresh()
    if &filetype ==# 'nerdtree'
        silent exe substitute(mapcheck('R'), '<CR>', '', '')
    endif
endfunction

autocmd BufEnter * call NERDTreeRefresh()

" git symbol definitions
let g:NERDTreeIndicatorMapCustom = {
\   'Modified'  : '✹',
\   'Staged'    : '✚',
\   'Untracked' : '✭',
\   'Renamed'   : '➜',
\   'Unmerged'  : '═',
\   'Deleted'   : '✖',
\   'Dirty'     : '✗',
\   'Clean'     : '✔︎',
\   'Ignored'   : '☒',
\   'Unknown'   : '?'
\ }


" NERDTree thingy
let g:NERDTreeDirArrows = 1
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
let NERDTreeMinimalUI=1

" Hide .pyc files in NERDTree
let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree"

"""" RUNVIEW """"""""""""""""""""""""""""""""""""""""""""
" runview works with python
let g:runview_filtcmd='python3.6'

" check file extension and parse appropriate command to runview and assign to F12
let extension_dict = {
\    'py': '%RunView!python3.6',
\    'sh': '%RunView!sh',
\    'js': '%RunView!node'
\ }
let extension_command = get(extension_dict, expand('%:e'))

"""" MARKDOWN SETTINGS """"""""""""""""""""""""""""""""""""""""""""""""""
" makes all markdown previews in GitHub style
let vim_markdown_preview_github=1

if expand('%:e') ==# 'md'
  set spell spelllang=en_gb
  set background=light
  colorscheme pencil
endif

"""" EMMET """""""""""""""""""""""""""""""""""""""""""""""""""""""
" enable emmet only for HTML and CSS files
let g:user_emmet_install_global = 0
autocmd FileType html,css,jsx,javascript EmmetInstall

let g:user_emmet_leader_key=','
let g:user_emmet_settings = {
\  'javascript.jsx' : {
\      'extends' : 'jsx',
\      'quote_char': "'",
\  },
\ }
