"""" GLOBALS """""""""""""""""""""""""""""""""""
let g:vimrc = resolve(expand('<sfile>:p'))
let g:vimdir = fnamemodify(vimrc, ':h')

" for picobook
let g:notesdir = fnamemodify(vimdir, ':h') . '/notes/'
let g:noteurl = 'https://github.com/superDross/dotfiles/blob/master/notes/'

function! SourceBaseRc(f)
  exec 'source ' . g:vimdir . '/' . a:f
endfunction

"""" PLUGINS """"""""""""""""""""""""""""""""""""""""
call plug#begin()

call SourceBaseRc('base.vimrc')

" TESTING FRAMEWORK: unit testing
Plug 'junegunn/vader.vim'

" TAG BROWSER: get class/function names in a sidebar
Plug 'liuchengxu/vista.vim'

" LINTER: syntax checkers
Plug 'w0rp/ale'

" HIGHLIGHTING: syntax highlighters for non-python languages
Plug 'sheerun/vim-polyglot'

" GIT: use git/mercurial commands in vim e.g. Gblame
Plug 'tpope/vim-fugitive'
Plug 'mhinz/vim-signify'
Plug 'rhysd/git-messenger.vim'

"MARKDOWN: preview markdown files
Plug 'masukomi/vim-markdown-folding'

"OUTPUT: execute commands in a new buffer
Plug 'vim-scripts/RunView'

"HIGHLIGHTING: highlights regex changes during typing
Plug 'markonm/traces.vim'
Plug 'machakann/vim-highlightedyank'

" COLORSCHEMES: various colorschemes
Plug 'morhetz/gruvbox'
Plug 'huyvohcmc/atlas.vim'
Plug 'srcery-colors/srcery-vim'

" EDITING: further improve editing
Plug 'machakann/vim-sandwich'
Plug 'machakann/vim-swap'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-abolish'
Plug 'wellle/targets.vim'

" HTML: automates HTML tags (check tutorial)
Plug 'mattn/emmet-vim', { 'for': ['javascript', 'html', 'css'] }

" STATUSLINE: lightweight status line
Plug 'itchyny/lightline.vim'
Plug 'maximbaz/lightline-ale'

" FILEFINDER: fuzzy file finder
" needs to be installed locally too
if has('macunix')
  Plug '/usr/local/opt/fzf'
else
  Plug '~/.fzf'
endif
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" TAB RENAMING: allows one to rename vim tabs and sustain them over sessions
Plug 'gcmt/taboo.vim'

" PERSONAL: my plugins
Plug 'superDross/class-builder'
Plug 'superDross/ticket.vim'
Plug 'superDross/picobook'

" TRAINING: git gud @ vim
Plug 'takac/vim-hardtime'

call plug#end()

"""" COLOURS """""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" deepen gruvbox contrast
let g:gruvbox_contrast_dark = 'hard'
let g:gruvbox_sign_column = 'bg0'
let g:gruvbox_color_column = 'bg0'
colorscheme gruvbox

" sets background truly black and whites truly white
" highlight Normal guibg=black guifg=white

" match terminal background color
" highlight Normal guibg=#0F0F0F ctermbg=0

"""" CUSTOM KEY BINDINGS """"""""""""""""""""""""""""""""""""""
" remap folding
nnoremap <leader><leader> za

" function keys
nnoremap <leader>4 :ALEFix<CR>
nnoremap <leader>8 :Vista!!<CR>
nnoremap <buffer> <leader>9 :exec extension_command<Bar>exec 'resize 40'<CR>

" ALE shortcuts
nnoremap <silent> <leader>h :ALEHover<CR>
nnoremap <silent> <leader>r :ALEFindReferences<CR>
nnoremap <silent> <leader>j :ALENext<CR>
nnoremap <silent> <leader>k :ALEPrevious<CR>
nnoremap <silent> <Leader>d :ALEGoToDefinition<CR>
nnoremap <silent> <Leader>n :ALEGoToDefinitionInTab<CR>
nnoremap <silent> <Leader>v :ALEGoToDefinitionInVSplit<CR>
nnoremap <silent> <Leader>x :ALEGoToDefinitionInSplit<CR>

" fuzzy file/word finder key
nnoremap <leader>f :FZF<CR>
nnoremap <Leader>a :Ag<CR>
nnoremap <Leader>g :Rg<CR>
nnoremap <Leader>b :Buffers<CR>
nnoremap <Leader>c :Commits<CR>
nnoremap <Leader>* :execute 'Ag' expand('<cword>')<CR>

"""" TAB COMPLETION """"""""""""""""""""""""""""""""""""""""""""""""
" not sure what this does but is required for tab completion
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Completion Bound to TAB
inoremap <silent> <expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ '<C-\><C-O>:ALEComplete<CR>'
inoremap <silent> <expr><S-TAB> pumvisible() ? "\<C-p>" : ""

" Go to newline when popup menu is active instead of selecting completion
inoremap <silent> <expr> <CR>
      \ pumvisible() ? "<CR><CR>" : "<CR>"

" auto close preview window when the popup menu is not visible
autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif

"""" ALE """"""""""""""""""""""""""""""""""""""""""""""""
" only use autopep8 ale fixer on work laptop
if system('uname -n | tr -d "\n"') ==# 'david-work'
  let auto = 'autopep8'
else
  let auto = 'black'
endif

let g:ale_fixers = {
      \    '*': ['remove_trailing_lines', 'trim_whitespace'],
      \    'python': ['isort', 'black'],
      \    'c': ['clang-format'],
      \    'sh': ['shfmt'],
      \    'javascript': ['eslint'],
      \    'json': ['jq'],
      \    'html': ['prettier'],
      \    'css': ['prettier', 'stylelint'],
      \    'markdown': ['prettier'],
      \    'rust': ['rustfmt'],
      \    'sql': ['sqlformat'],
      \ }

" fixer args
let g:ale_python_isort_options = '-ws -tc -o=tabulate -w "88"'
let g:ale_sql_sqlformat_options = '--keywords upper --identifiers lower'

" npm install typescript for completion to work in a local project
" Install:
"   python-language-server, tsserver, bash-language-server,
"   stylelint, csslint, jsonlint, mdl, vint, gitlint,
"   shellcheck
let g:ale_linters = {
      \   'javascript': ['flow', 'eslint', 'tsserver'],
      \   'python': ['pyls'],
      \   'cfn': ['cfn-lint'],
      \   'rust': ['rls', 'cargo'],
      \   'sql': ['sqlint'],
      \ }

" completion settings
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 30
let g:ale_lint_delay = 0

" linter msg formatting
let g:ale_echo_msg_format = '%s [%linter%]'

" change signs
let g:ale_sign_error = '>>'
let g:ale_sign_warning = '--'

" underline errors
highlight ALEError ctermbg=none cterm=underline
" highlight ALEWarning ctermbg=none cterm=underline

" ALEHover in popup (NOT YET WORKING, in a PR)
let g:ale_set_popups = 1

"""" FZF """""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" use ag instead of find, whcih is faster and repects .gitignore
let $FZF_DEFAULT_COMMAND = 'ag -g ""'

if v:version >= 802 || has('nvim-0.4')
  let g:fzf_layout = {
\   'window': {
\     'width': 0.9,
\     'height': 0.6,
\     'highlight': 'Todo',
\     'border': 'sharp'
\   }
\ }
endif

"""" LIGHTLINE """"""""""""""""""""""""""""""""""""""""""""""""""""""""
" no longer show mode in bottom line
set noshowmode

let g:lightline#ale#indicator_warnings =  '⏶ '
let g:lightline#ale#indicator_errors = '✘ '

" show git branch in status line
let g:lightline = {
\ 'active': {
\     'left': [ [ 'mode', 'paste'],
\               [ 'readonly',  'gitbranch', 'gutentags'],
\               ['filename', 'modified' ] ],
\     'right': [ [ 'lineinfo' ],
\                [ 'percent' ],
\                [ 'bufnum' ],
\                [ 'linter_errors', 'linter_warnings'] ]
\   },
\ 'component_function': {
\     'gitbranch': 'fugitive#head',
\     'gutentags': 'gutentags#statusline',
\   },
\ 'component_expand': {
\     'linter_warnings': 'lightline#ale#warnings',
\     'linter_errors': 'lightline#ale#errors',
\   },
\ 'component_type': {
\     'linter_warnings': 'warning',
\     'linter_errors': 'error',
\   },
\ }


if g:colors_name ==# 'gruvbox'
  let g:lightline.colorscheme = 'gruvbox'
endif

"""" POLYGLOT """""""""""""""""""""""""""""""""""""""""""""""""""""""""
" work around for the PolyGlot GraphQL error in Javascript files
let g:polyglot_disabled = ['graphql', 'markdown']

"""" TABOO """""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" sustain tab names over sessions
set sessionoptions+=tabpages,globals

" naming format
let g:taboo_renamed_tab_format = ' %l %m '

"""" VISTA """""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:vista#renderer#enable_icon = 0

"""" RUNVIEW """"""""""""""""""""""""""""""""""""""""""""
" runview works with python
let g:runview_filtcmd='python3'

" check file extension and parse appropriate command to runview and assign to F12
let extension_dict = {
\    'py': '%RunView!python3',
\    'sh': '%RunView!sh',
\    'js': '%RunView!node'
\ }
let extension_command = get(extension_dict, expand('%:e'))

"""" EMMET """""""""""""""""""""""""""""""""""""""""""""""""""""""
" enable emmet only for HTML and CSS files
let g:user_emmet_install_global = 0
autocmd FileType html,css,jsx,javascript EmmetInstall

let g:user_emmet_leader_key=','
let g:user_emmet_settings = {
\  'javascript.jsx' : {
\      'extends' : 'jsx',
\      'quote_char': "'",
\  },
\ }

"""" HARDTIME """""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:hardtime_default_on = 1
let g:hardtime_showmsg = 1
let g:hardtime_ignore_quickfix = 1
let g:hardtime_allow_different_key = 1
let g:hardtime_maxcount = 5
