"""" GLOBALS """""""""""""""""""""""""""""""""""
let g:vimrc = resolve(expand('<sfile>:p'))
let g:vimdir = fnamemodify(vimrc, ':h')

" for picobook
let g:notesdir = fnamemodify(vimdir, ':h') . '/notes/'
let g:noteurl = 'https://github.com/superDross/dotfiles/blob/master/notes/'
let g:browser = 'chromium'

function! SourceBaseRc(f)
  exec 'source ' . g:vimdir . '/' . a:f
endfunction

function! GitLinePopUp()
  " like git-messanger but with a popup
  " TODO: clean up
  call setbufvar(winbufnr(popup_atcursor(systemlist("cd " . shellescape(fnamemodify(resolve(expand('%:p')), ":h")) . " && git log --no-merges -n 1 -L " . shellescape(line("v") . "," . line(".") . ":" . resolve(expand("%:p")))), { "padding": [1,1,1,1], "pos": "botleft", "wrap": 0 })), "&filetype", "git")
endfunction

"""" POLYGLOT """""""""""""""""""""""""""""""""""""""""""""""""""""""""
" work around for the PolyGlot GraphQL error in Javascript files
let g:polyglot_disabled = ['graphql', 'markdown']

"""" PLUGINS """"""""""""""""""""""""""""""""""""""""
call plug#begin()

call SourceBaseRc('base.vimrc')

" TESTING FRAMEWORK: unit testing
Plug 'junegunn/vader.vim'

" UNDOTREE: visualise undotrees
if has('nvim') || has('python3') || has('python')
  Plug 'simnalamburt/vim-mundo'
else
  Plug 'mbbill/undotree'
endif

" TAG BROWSER: get class/function names in a sidebar
Plug 'liuchengxu/vista.vim'

" LINTER: syntax checkers
Plug 'w0rp/ale'

" HIGHLIGHTING: syntax highlighters for non-python languages
Plug 'sheerun/vim-polyglot'

" GIT: use git/mercurial commands in vim e.g. Gblame
Plug 'tpope/vim-fugitive'
Plug 'mhinz/vim-signify'

"MARKDOWN: preview markdown files
Plug 'masukomi/vim-markdown-folding'

"HIGHLIGHTING: highlights regex changes during typing
Plug 'markonm/traces.vim'
Plug 'machakann/vim-highlightedyank'

" COLORSCHEMES: various colorschemes
Plug 'morhetz/gruvbox'
Plug 'huyvohcmc/atlas.vim'
Plug 'srcery-colors/srcery-vim'

" EDITING: further improve editing
Plug 'machakann/vim-sandwich'
Plug 'tpope/vim-commentary'
Plug 'wellle/targets.vim'

" STATUSLINE: lightweight status line
Plug 'itchyny/lightline.vim'
Plug 'maximbaz/lightline-ale'

" FILEFINDER: fuzzy file finder
" needs to be installed locally too
if has('macunix')
  Plug '/usr/local/opt/fzf'
else
  Plug '~/.fzf'
endif
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
" for FZFMarks only
Plug 'chengzeyi/fzf-preview.vim'

" TAB RENAMING: allows one to rename vim tabs and sustain them over sessions
Plug 'gcmt/taboo.vim'

" PERSONAL: my plugins
Plug 'superDross/class-builder'
Plug 'superDross/ticket.vim'
Plug 'superDross/picobook'
Plug 'superDross/run-with-me.vim'
Plug 'superDross/scrappy.vim'

call plug#end()

"""" COLOURS """""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" deepen gruvbox contrast
let g:gruvbox_contrast_dark = 'hard'
let g:gruvbox_sign_column = 'bg0'
let g:gruvbox_color_column = 'bg0'
colorscheme gruvbox

" sets background truly black and whites truly white
" highlight Normal guibg=black guifg=white

" match terminal background color
" highlight Normal guibg=#0F0F0F ctermbg=0

"""" CUSTOM KEY BINDINGS """"""""""""""""""""""""""""""""""""""
" remap folding
nnoremap <leader><leader> za

" function keys
nmap <leader>1 <Plug>(run_tests)
nmap <leader>2 <Plug>(create_scratchpad_vertical)
nnoremap <leader>4 :ALEFix<CR>
nnoremap <leader>8 :Vista!!<CR>
nmap <leader>9 <Plug>(run_code)

" ALE shortcuts
nnoremap <silent> <leader>h :ALEHover<CR>
nnoremap <silent> <leader>r :ALEFindReferences -relative<CR>
nnoremap <silent> <leader>j :ALENext<CR>
nnoremap <silent> <leader>k :ALEPrevious<CR>
nnoremap <silent> <Leader>d :ALEGoToDefinition<CR>
nnoremap <silent> <Leader>n :ALEGoToDefinition -tab<CR>
nnoremap <silent> <Leader>v :ALEGoToDefinition -vsplit<CR>
nnoremap <silent> <Leader>x :ALEGoToDefinition -split<CR>

" undo tree
if has('nvim') || has('python3') || has('python')
  nnoremap <silent> <Leader>u :MundoToggle<CR>
else
  nnoremap <silent> <Leader>u :UndotreeToggle<CR>
endif

" fuzzy file/word finder key
nnoremap <leader>f :FZF<CR>
nnoremap <Leader>a :RgContents<CR>
nnoremap <Leader>g :Rg<CR>
nnoremap <Leader>b :Buffers<CR>
nnoremap <Leader>c :Commits<CR>
nnoremap <Leader>` :FZFMarks<CR>
nnoremap <Leader>* :execute 'Ag' expand('<cword>')<CR>
nnoremap <silent><Leader>m :call GitLinePopUp()<CR>

"""" TAB COMPLETION """"""""""""""""""""""""""""""""""""""""""""""""
" not sure what this does but is required for tab completion
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Completion Bound to TAB
inoremap <silent> <expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ '<C-\><C-O>:ALEComplete<CR>'
inoremap <silent> <expr><S-TAB> pumvisible() ? "\<C-p>" : ""

" Go to newline when popup menu is active instead of selecting completion
inoremap <silent> <expr> <CR>
      \ pumvisible() ? "<CR><CR>" : "<CR>"

" auto close preview window when the popup menu is not visible
autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif

"""" ALE """"""""""""""""""""""""""""""""""""""""""""""""
let g:ale_fixers = {
      \    '*': ['remove_trailing_lines', 'trim_whitespace'],
      \    'python': ['isort', 'black'],
      \    'c': ['clang-format'],
      \    'sh': ['shfmt'],
      \    'javascript': ['eslint'],
      \    'json': ['jq'],
      \    'html': ['prettier'],
      \    'css': ['prettier', 'stylelint'],
      \    'markdown': ['prettier'],
      \    'rust': ['rustfmt'],
      \    'sql': ['sqlformat'],
      \ }

" fixer args
let g:ale_python_isort_options = '-ws -tc -o=tabulate -w "88"'
let g:ale_sql_sqlformat_options = '--keywords upper --identifiers lower'

" npm install typescript for completion to work in a local project
" Install:
"   python-language-server, tsserver, bash-language-server,
"   stylelint, csslint, jsonlint, mdl, vint, gitlint,
"   shellcheck
let g:ale_linters = {
      \   'javascript': ['flow', 'eslint', 'tsserver'],
      \   'python': ['pylsp'],
      \   'cfn': ['cfn-lint'],
      \   'rust': ['rls', 'cargo'],
      \   'sql': ['sqlint'],
      \ }

" completion settings
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 30
let g:ale_lint_delay = 0

" linter msg formatting
let g:ale_echo_msg_format = '%s [%linter%]'

" change signs
let g:ale_sign_error = '>>'
let g:ale_sign_warning = '--'

" underline errors
highlight ALEError ctermbg=none cterm=underline
" highlight ALEWarning ctermbg=none cterm=underline

" ALEHover in preview
let g:ale_hover_to_preview = 1

"""" FZF """""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" use ag instead of find, whcih is faster and repects .gitignore
let $FZF_DEFAULT_COMMAND = 'ag -g ""'

if v:version >= 802 || has('nvim-0.4')
  let g:fzf_layout = {
\   'window': {
\     'width': 0.9,
\     'height': 0.6,
\     'highlight': 'Todo',
\     'border': 'sharp'
\   }
\ }
endif

" use Rg but to not match file names when using Rg in Fzf
command! -bang -nargs=* RgContents
      \ call fzf#vim#grep(
      \ 'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
      \ fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}), <bang>0
      \)

"""" LIGHTLINE """"""""""""""""""""""""""""""""""""""""""""""""""""""""
" no longer show mode in bottom line
set noshowmode

let g:lightline#ale#indicator_warnings =  '⏶ '
let g:lightline#ale#indicator_errors = '✘ '

" show git branch in status line
let g:lightline = {
\ 'active': {
\     'left': [ [ 'mode', 'paste'],
\               [ 'readonly',  'gitbranch', 'gutentags'],
\               ['filename', 'modified' ] ],
\     'right': [ [ 'lineinfo' ],
\                [ 'percent' ],
\                [ 'bufnum' ],
\                [ 'linter_errors', 'linter_warnings'] ]
\   },
\ 'component_function': {
\     'gitbranch': 'fugitive#head',
\     'gutentags': 'gutentags#statusline',
\   },
\ 'component_expand': {
\     'linter_warnings': 'lightline#ale#warnings',
\     'linter_errors': 'lightline#ale#errors',
\   },
\ 'component_type': {
\     'linter_warnings': 'warning',
\     'linter_errors': 'error',
\   },
\ }


if g:colors_name ==# 'gruvbox'
  let g:lightline.colorscheme = 'gruvbox'
endif

"""" TABOO """""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" sustain tab names over sessions
set sessionoptions+=tabpages,globals

" naming format
let g:taboo_renamed_tab_format = ' %l %m '

"""" VISTA """""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:vista#renderer#enable_icon = 0

"""" UNDOTREE """""""""""""""""""""""""""""""""""""""""""""""""""
let g:undotree_WindowLayout = 2
let g:undotree_ShortIndicators = 1

let g:mundo_width = 60

"""" PERSONAL """""""""""""""""""""""""""""""""""""""""""""""""""
let g:default_testing_cmd = "make test"
