# Allows you to save tmux sessions even after reboots
# Save    ->  Ctrl-b + Ctrl-s
# Restore ->  Ctrl-b + Ctrl-r

# PLUGINS
# prefix + I to install
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run '~/.tmux/plugins/tpm/tpm'

# allow vim sessions to be saved
# set -g @resurrect-strategy-vim 'session'


########################
#      GENERAL         #
########################

setw -g mouse on

# allow true colours
# set -g default-terminal "xterm-256color"
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

# start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1


########################
#      STATUS BAR      #
########################

# set-option -g status-position top

# postioning
set-option -g status-justify centre
set -g status-left " #S "
set -g status-left-length 60
set -g status-right "#H "
set -g status-right-length 60

# colours
set-option -g status-style bg=#333333,fg=white
set-window-option -g window-status-style bg=#333333,fg=white
# set-window-option -g window-status-current-style bg=#E55B0A,fg=black
set-window-option -g window-status-current-style bg=colour41,fg=black
set-window-option -g window-status-separator '  '


########################
#      WINDOW STYLE    #
########################

# setw -g window-style 'bg=#262626'
# setw -g window-active-style 'bg=#121212'
set-option -ag pane-active-border-style fg=white
set-option -g pane-border-style fg=#3a3d3d


########################
#      KEY BINDINGS    #
########################

# vim-like pane resizing
bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R

# vim-like pane switching
bind -r j select-pane -U
bind -r k select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# and now unbind keys
unbind Up
unbind Down
unbind Left
unbind Right

unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right
