#### UBUNTU DEFAULTS
# ~/.bashrc: executed by bash(1) for non-login shells.
# for examples
# set -x
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


#### PATHS
export PATH=$PATH:$HOME/bin/vcfhacks:$HOME/key-scripts/csq_query.py:$HOME/bin/dapPerlGenomicLib:$HOME/.cargo/bin:$HOME/configuration/ideas/bash/:$HOME/bin/vcfhacks/
export PERL5LIB=$PERL5LIB:$HOME/bin/vcfhacks:$HOME/bin/dapPerlGenomicLib:$HOME/bin/vcftools/src/perl/
# start up pythonrc to get autocomplete and saving of python environment in python shell
export PYTHONSTARTUP=$HOME/.pythonrc

# point python-path to some user made functions/modules
if [ -d ~/key-scripts/ ]; then
	export `python3 ~/key-scripts/pythonpath.py /home/${USER}/projects/`
fi


#### FUNCTIONS
# Usage: findpy "Driver ID"
ffind() {
	find . -type f -name "*.$1" ! -path '*/venv/*' | xargs grep "${@:2}"
}

# parse git or hg branch name
parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
	 hg branch 2> /dev/null | awk '{ print " hg (" $1 ")" }'
}

# multiple git 'aliases'
git(){
	if [[ $@ == 'graph' ]]; then
		command git log --graph --oneline --decorate --all
	else
		command git "$@"
	fi
}

# go up x many dirs:
#     up 2 == cd ../../
up() {
    if [[ "$#" == 0 ]] ; then
        cd ..
    else
        CDSTR=""
        for i in $(seq 1 $1) ; do
            CDSTR="../$CDSTR"
        done
        cd $CDSTR
    fi
}

# stream torrent magnet in VLC
vlc_stream() {
  # use CTRL+Z and then type `bg` to take back your terminal
  peerflix "$1" --remove --vlc --quiet --list
}

# intiate the dbgp debugger for vim
debug() {
  if [ "$1" != "python2" ] && [ "$1" != "python3" ]; then
    local py_version="python3"
    local args="$@"
  else
    local py_version="$1"
    local args="${@:2}"
  fi
  ${py_version} -S ~/.vim/debuggers/${py_version}/pydbgp -d localhost:9000 $args
}

#### ALIASES
# hide unwanted files, make directories first shown, then show files.
alias ls='ls \
            --color=auto \
            --hide="*.pyc" \
            --hide="*.egg-info" \
            --hide="__pycache__" \
            --group-directories-first \
            --sort=extension'

# allows sudo to work with alias command
alias sudo='sudo '

# sets up volume, second monitor & xbox controller for steam big picture mode
alias game-on="/home/${USER}/key-scripts/game-on.sh"

# as above without volume
alias game-quietly="/home/${USER}/key-scripts/game-quietly.sh"

# shorthand for connecting to remote
alias osmc="ssh osmc@192.168.1.7"

# shorthand for software
alias tree="tree -I '*.egg-info|*.pyc|__pycache__|__init__.py'"

# copy a file, usage: `copy <file>`
alias copy="xclip -sel c <"

# an alias for clear and list details & another with details
alias cls="clear; ls"
alias cll="clear; ls -lh"
alias c="clear"

alias h="history"
alias hsi="history | grep"

# set up work environment for local instances
alias vel="cd ~/dev/velocity/; source bin/activate; export DJANGO_SETTINGS_MODULE=velocity.settings.servers.developers.dev_david_ro; export CELERY_LOADER=velocity.celeryloader.DjangoLoader"
alias jvel="vel; cd ~/projects/velocitynotes/jupyter_notebooks/; jupyter notebook"
alias er="cd ~/dev/eroute/; source venv/bin/activate; export DJANGO_SETTINGS_MODULE=gmaps.dev_david_ro"

# fix resolve.conf for work VPN
alias fix_vpn="sudo echo -e 'nameserver 10.200.53.10\nnameserver 10.200.23.10\nsearch crewe.ukfuels.co.uk' > /etc/resolv.conf"

alias dragonball='vlc_stream "magnet:?xt=urn:btih:a90c45f9c0c9b07435d1aad8564077b2ac7591aa"'

#### COLOURS
# change the colour of the dirs and executable files
export LS_COLORS=$LS_COLORS:'di=1;35;95:ex=1;32;33:fi=0:ln=1;31:*.md=0;37'

# Cloured Man Pages
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

# coloured less pages
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R '

#### EDITOR
# vim to be default editor
export VISUAL=vim
export EDITOR="$VISUAL"
export VIMRC=~/.vimrc


#### PLUGINS
# install these plugins
# https://github.com/wting/autojump
# https://github.com/junegunn/fzf

# source plugins
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[[ -s /home/${USER}/.autojump/etc/profile.d/autojump.sh ]] && source /home/${USER}/.autojump/etc/profile.d/autojump.sh

# add git branch to prompt
export PS1="\u \w\[\033[32m\]\$(parse_git_branch)\[\033[00m\] $ "
export PATH=/home/david/.nimble/bin:$PATH
