###################
#    VARIABLES    #
###################

# store operating system
OS=$(uname -s)

# no colour reset
NC='\033[0m'
# all light colours
GRAY='\033[1;30m'
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
CYAN='\033[1;36m'
WHITE='\033[1;37m'

BROWSER=/usr/bin/firefox


#################
#    MAC        #
#################

if [[ "$OS" == "Darwin" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
  # alias python="/opt/homebrew/bin/python3"

  # Beamery Cluster 2.0 Tooling
  export PATH=${HOME}/.beamery-tooling/bin:$PATH

  # Ensure google cloud behaves
  export USE_GKE_GCLOUD_AUTH_PLUGIN=True
  source '/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc'

  # Beamery Vault Access
  token=$(cat ~/.gh_token)
  export GITHUB_API_TOKEN=$token
  vault_login() {
    environment=${1:-global}
    export VAULT_ADDR="https://vault.${environment//-/.}.beamery.engineer"
    unset VAULT_TOKEN
    vault token lookup &>/dev/null || vault login -method=github token="${GITHUB_API_TOKEN}"
  }

  # Bash Completion
  [[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"
fi


#################
#    ALIASES    #
#################

# system specific aliases
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# use gls for macs
[[ $OS = 'Darwin' ]] && list='gls' || list='ls'

# rename executables
alias h='history'
alias extract='unp'
alias vi='vim'

# hide unwanted files, make directories first shown, then show files.
alias ls='$list --color=auto --hide="*.pyc" --hide="*.egg-info" --hide="__pycache__" --group-directories-first --sort=extension'
alias ll='ls -alF'

# try neovim for a while
alias vim='nvim'

# grep colours
alias grep='grep --color=auto'

# custom grep commands
alias hgrep="history | grep"
alias psgrep='ps aux |grep -v grep |grep -i'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias count='du -a | cut -d/ -f2 | sort | uniq -c | sort -nr'
alias bsource='source ~/.bashrc'

# allows sudo to work with alias command
alias sudo='sudo '

# used for debugging with docker and remote-pdb
alias debug='rlwrap nc 127.0.0.1 4444'

# SSH shorthands
alias osmc="ssh osmc@192.168.1.7"

# various tools I forget the names to
alias epub="foliate"
alias screen-recorder="simplescreenrecorder"
alias gif-recorder="peek"

# prevent all the clutter from appearing in tree
alias tree="tree -I '*.egg-info|*.pyc|__pycache__|node_modules'"

# copy a file, usage: `copy <file>`
if [[ $OS = 'Darwin' ]]; then
  alias copy="pbcopy <"
else
  alias copy="xclip -sel c <"
fi

# an alias for clear and list details & another with details
alias cls="clear; ls"
alias cll="clear; ls -lh"
alias c="clear"

# fix pirate-get error
alias pirate-get="PYTHONIOENCODING=utf-8 pirate-get"

# docker_plus alias
alias dp="docker_plus"
alias kp="kubectl --context minikube -n play"
alias tf="terraform"

# work screen layout
alias workscreen="bash ~/.screenlayout/work.sh"

# ebook reader
alias ebook="foliate"

# jetbrains toolbox
alias jetbrains="~/bin/jetbrains-toolbox-1.21.9712/jetbrains-toolbox"

####################
#    FUNCTIONS     #
####################

function fuzzy-kill() {
  # BE CAREFUL: kills all processes containing the given substring
  if [[ -z "$1" ]]; then
    echo "You must provide an argument"
  fi
  sudo kill $(ps -aef | grep "$1" | awk '{print $2}' | xargs)
}

function docker_stop_all(){
  # not using `docker ps -q` as we want to make minikube an exception
  containers=$(docker ps | tail -n +2 | grep -v minikube | awk '{print $1}')
  docker stop $containers
}

function docker_plus_help(){
cat <<- EOF
Commands:
  logs: see containers logs
  bash: jump into a containers bash shell
  psql: jump into a postgres containers psql shell
EOF
}

function docker_clean_up(){
  read -p "[WARNING] this will remove all Docker related files. Continue? (y/n) $ " answer
  case $answer in
    y | yes | Y | YES)
      docker system prune --force
      docker container stop $(docker container ls -aq)
      docker container rm $(docker container ls -aq)
      docker rmi $(docker images -aq)
      docker volume prune --force
      ;;
    n | no | N | NO)
      echo "Exiting..."
      ;;
    *)
      echo "Answer ${answer} unknown. Exiting..."
      ;;
  esac

}


function remove_debugger() {
  # Removes all python debugger statements from py files in a given dir
  #   $1: directory to recursively search for py files must be absolute path (default: current directory)

  directory="$1"
  suffix="py"

  if [ -z "$1" ]; then
    directory=$(pwd)
  fi

  message=$(\
    rg \
    'import pdb.*|.*pdb.set_trace.*|.*remote_pdb.*|.*RemotePdb.*|.*breakpoint\(\)' \
    --type $suffix \
    --pretty \
    $directory \
  )
  # get only the file names (sed removes colours)
  files=$(echo "$message" | sed 's/\x1b\[[0-9;]*m//g' | grep "\.${suffix}\>")

  # remove the 4444:4444 exposed port liness from the docker-compose files
  port_message=$(rg --files -g '*docker-compose.*' | xargs rg --pretty '4444:4444')
  docker_files=$(echo "$port_message" | sed 's/\x1b\[[0-9;]*m//g' | rg "docker-compose")

  if [ -z "$message" ] && [ -z "$port_message" ]; then
    echo "No debugging statements found. Exiting..."
    return 0
  fi

  echo "$message"
  echo "$port_message"
  read -p "Do you want to remove the above debugger lines? (y/n) $ " answer

  case $answer in
    y | yes | Y | YES)
      echo $files $docker_files | \
        xargs sed --in-place \
        '/import pdb/d;/pdb.set_trace/d;/remote_pdb/d;/RemotePdb/d;/breakpoint()/d;/4444:4444/d'
      echo "Complete"
      ;;
    n | no | N | NO)
      echo "Exiting..."
      ;;
    *)
      echo "Answer ${answer} unknown. Exiting..."
      ;;
  esac
}

function lua_debugger_download(){
  # Download lua debugger into current directory
  # TODO: would be nice to implement this as part of the lua snippet instead
  echo -e "${GREEN}Downloading debugger...${NC}\n"
  wget -nv \
    https://raw.githubusercontent.com/slembcke/debugger.lua/master/debugger.lua \
    -O debugger.lua
  echo -e "\n${GREEN}Add ${YELLOW}local dbg = require('debugger')${GREEN} to your lua script to import it."
  echo -e "Then execute ${YELLOW}nvim --headless${GREEN} to trigger the debugger.${NC}"
}

function docker_plus(){
  # Wrapper for some docker cli commands: 
  #   $1: docker_plus command
  #   $2: part or full container name
  if [ -z "$(docker ps -q)" ]; then
    echo "No docker containers are running."
    return
  fi
  container_id=$(docker ps | awk '$NF ~ /'$2'/ {print $1}' | head -n 1)
  container_name=$(docker ps | awk '$NF ~ /'$2'/ {print $NF}' | head -n 1)
  case $1 in
    help)
      docker_plus_help
      ;;
    logs | log)
      echo -e "Getting logs for ${YELLOW}${container_name}${NC}..."
      sleep 1
      docker logs $container_id -f
      ;;
    bash)
      echo -e "Jumping into ${YELLOW}${container_name}${NC} bash shell..."
      sleep 1
      docker exec -it $container_id /bin/bash
      ;;
    shell)
      echo -e "Jumping into ${YELLOW}${container_name}${NC} shell..."
      sleep 1
      docker exec -it $container_id /bin/sh
      ;;
    psql)
      # $3: database name
      db_name=$([ -z "$3" ] && echo "postgres" || echo "$3")
      echo -e "Jumping into ${YELLOW}${container_name}${NC} (${db_name}) psql shell..."
      sleep 1
      docker exec -it $container_id psql -U postgres -d $db_name
      ;;
    *)
      echo "ERROR: ${2} is not a valid command. See 'docker_plus help'."
      ;;
  esac
}


# parse git or hg branch name and stash number
function parse_git_branch() {
  if [[ $(command -v git) ]]; then
    if git ls-files >&/dev/null; then
      branch=$(git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
      # remove feature/bugfix etc. from branch name
      branch_without_prefix=$(echo $branch | sed 's/[a-zA-Z].*\///')
      stash_num=$(git stash list | grep "$branch_without_prefix" | wc -l | sed 's/^ *//g')
      if [ "$stash_num" = 0 ]; then
        echo " (${branch})"
      else
        echo " (${branch}) ${stash_num}"
      fi
    elif [ -d .hg ]; then
      hg branch 2>/dev/null | awk '{ print " hg (" $1 ")" }'
    fi
  fi
}

function bg_process_num() {
  num=$(jobs | grep -c -v "autojump\|wezterm" | sed 's/^ *//g')
  if [ "$num" != 0 ]; then
    echo " $num"
  fi
}

# go up x many dirs:
#    up 2 == cd ../../
function up() {
  if [[ "$#" == 0 ]]; then
    cd ..
  else
    CDSTR=""
    for i in $(seq 1 $1); do
      CDSTR="../$CDSTR"
    done
    cd $CDSTR
  fi
}

# $1: service name
# $2: port
# $3: namespace (optional)
# $4: beamery environment (optional)
# example, prometheus in candidate-matching: port_forward_synergy candidate 8008
function port_forward_synergy() {
  if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo -e "\n${YELLOW}port_forward_synergy${NC} port forward to synergy service in staging env"
    echo -e "${BLUE}Usage${NC}:\t\tport_forward_synergy <service_name> <port> <namespace> <beam_env>"
    echo -e "${PURPLE}Example${NC}:\tport_forward_synergy candidate 8002 synergy beamery-staging\n"
    return 0
  fi
  namespace="${3:-synergy}"
  beam_env="${4:-beamery-staging}"
  service=$(kube_cloudflare.sh "$beam_env" kubectl -n "$namespace" get services | grep "$1" | awk 'FNR == 1{print $1}')
  kube_cloudflare.sh "$beam_env" kubectl -n "$namespace" port-forward "service/${service}" "${2}:${2}"
}


#################
#    OPTIONS    #
#################

# VI mode
set -o vi

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# append to the history file, don't overwrite it
shopt -s histappend

# Combine multiline commands into one in history
shopt -s cmdhist

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
# shopt -s globstar

# use dircolor options
# if [ -x /usr/bin/dircolors ]; then
#   test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
#   test -r ~/.dir_colors && eval "$(dircolors -b ~/.dir_colors)" || eval "$(dircolors -b)"
# fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion

  fi
fi


#################
#    HISTORY    #
#################

# don't put duplicate lines or lines starting with space in the history.
export HISTCONTROL=ignoreboth
export HISTSIZE=100000
export HISTFILESIZE=200000
# don't show repeated commands (&), ls, ls *, etc.
export HISTIGNORE="&:history:hgrep:h:cll:cll *:cls:c:c -A:[bf]g:fg:j:exit"
MY_BASH_GREEN="\033[38;5;82m"
MY_BASH_NOCOLOR="\033[0m"
HISTTIMEFORMAT=`echo -e ${MY_BASH_GREEN}[%F %T] $MY_BASH_NOCOLOR `


#################
#    COLOURS    #
#################

# change the colour of the dirs and executable files
# NOTE: see `dircolors` cmd & ~/.dir_colors for colouring specific extensions
export LS_COLORS=$LS_COLORS:'di=38;5;165:ex=38;5;226:fi=0:ln=38;5;204:*.md=0;37:*.txt=0;37'

# Cloured Man Pages
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

# coloured less pages
export LESSOPEN="| /usr/bin/src-hilite-lesspipe.sh %s"
export LESS=' -R '


#################
#    EDITOR     #
#################

export VISUAL=nvim
export EDITOR="$VISUAL"
export VIMRC=~/.vimrc


####################
#    DEVELOPMENT   #
####################

# Pyenv configuration
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# venv settings
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel

# PATH manipulation for various languages and tools
GEM_HOME=$(ruby -e 'puts Gem.user_dir')
export PATH=$PATH:$HOME/.npm-global/bin:$GEM_HOME/bin:$HOME/.cargo/bin:$HOME/.local/share/bob/nvim-bin:/usr/local/bin


#################
#    PLUGINS    #
#################

# source plugins
if [[ $OS = 'Darwin' ]]; then
  source /opt/homebrew/bin/virtualenvwrapper.sh
else
  source /usr/share/fzf/completion.bash
  source /usr/share/fzf/key-bindings.bash
  source /usr/bin/virtualenvwrapper.sh
fi

if [[ $OS = 'Darwin' ]]; then
  [[ -s /Users/David.Ross/.autojump/etc/profile.d/autojump.sh ]] && source /Users/David.Ross/.autojump/etc/profile.d/autojump.sh
else
  [[ -s /home/${USER}/.autojump/etc/profile.d/autojump.sh ]] && source /home/${USER}/.autojump/etc/profile.d/autojump.sh
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Use bash-completion, if available
[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
    . /usr/share/bash-completion/bash_completion

if command -v kubectl &> /dev/null
then
  source <(kubectl completion bash)
fi

if command -v helm &> /dev/null
then
  source <(helm completion bash)
fi

if command -v stern &> /dev/null
then
  source <(stern --completion=bash)
fi

if command -v terraform &> /dev/null
then
  [[ "$OS" = "Darwin" ]] && terr=/opt/homebrew/bin/terraform || terr=/usr/bin/terraform
  complete -C "$terr" terraform
fi


#################
#    PROMPT     #
#################

# Red username in prompt if remote accessing a computer
# Assumes hostname on original hardware has hostname with david in it
case $(hostname -s) in
david*)
  export USER_PS1="\u"
  ;;
*)
  export USER_PS1="\[\033[1;31m\]\u@\h\[\033[00m\]"
  ;;
esac

export PS1="$USER_PS1 \w"\
"\[\033[38;5;82m\]\$(parse_git_branch)\[\033[00m\]"\
"\[\033[38;5;87m\]\$(bg_process_num)\[\033[00m\] $ "
# "\e[38;5;202m\]\$(tmux_session_num)\[\033[00m\] $ "
