###################
#    VARIABLES    #
###################

# store operating system
os=$(uname -s)


#################
#    ALIASES    #
#################

# system specific aliases
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# use gls for macs
[[ $os = 'Darwin' ]] && list='gls' || list='ls'

# rename executables
alias h='history'
alias extract='unp'
alias vi='vim'

# hide unwanted files, make directories first shown, then show files.
alias ls='$list --color=auto --hide="*.pyc" --hide="*.egg-info" --hide="__pycache__" --group-directories-first --sort=extension'
alias ll='ls -alF'

# grep colours
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# custom grep commands
alias hgrep="history | grep"
alias psgrep='ps aux |grep -v grep |grep -i'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias count='du -a | cut -d/ -f2 | sort | uniq -c | sort -nr'
alias bsource='source ~/.bashrc'

# allows sudo to work with alias command
alias sudo='sudo '

# SSH shorthands
alias osmc="ssh osmc@192.168.1.7"

# prevent all the clutter from appearing in tree
alias tree="tree -I '*.egg-info|*.pyc|__pycache__|__init__.py|node_modules'"

# copy a file, usage: `copy <file>`
if [[ $os = 'Darwin' ]]; then
  alias copy="pbcopy <"
else
  alias copy="xclip -sel c <"
fi

# an alias for clear and list details & another with details
alias cls="clear; ls"
alias cll="clear; ls -lh"
alias c="clear"

# fix pirate-get error
alias pirate-get="PYTHONIOENCODING=utf-8 pirate-get"

# connect to vpn
computer=$(uname -n | tr -d "\n")
if [ "$computer" == 'david-work' ]; then
  # put 'push' as the second password
  alias vpn="sudo openconnect -v --user=david.ross --authgroup=yougov-duo --csd-wrapper=/usr/lib/openconnect/csd-post.sh ssluk.yougov.net"
  alias us_vpn="sudo openconnect -v --user=david.ross --authgroup=yougov-duo --csd-wrapper=/usr/lib/openconnect/csd-post.sh sslus.yougov.net"
else
  alias vpn="sudo openvpn --config ~/.openvpn/cz/openvpn.ovpn"
fi


####################
#    FUNCTIONS     #
####################

function ffind() {
  if cmd="$(type -p "rg")" || [[ -x $cmd ]]; then
    rg "${@:2}" --type "$1" -g '!**/venv/*' -g '!**/.tox/*'
  # add ag alternative
  else
    find . -type f -name "*.$1" ! -path '*/venv/*' ! -path '*/.tox/*' | xargs grep "${@:2}"
  fi
}

function ftype() {
  find . -iname "*.${@}"
}

# parse git or hg branch name and stash number
function parse_git_branch() {
  if [[ $(command -v git) ]]; then
    if git ls-files >&/dev/null; then
      branch=$(git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
      # remove feature/bugfix etc. from branch name
      branch_without_prefix=$(echo $branch | sed 's/[a-zA-Z].*\///')
      stash_num=$(git stash list | grep "$branch_without_prefix" | wc -l | sed 's/^ *//g')
      if [ "$stash_num" = 0 ]; then
        echo " (${branch})"
      else
        echo " (${branch}) ${stash_num}"
      fi
    elif [ -d .hg ]; then
      hg branch 2>/dev/null | awk '{ print " hg (" $1 ")" }'
    fi
  fi
}

function bg_process_num() {
  num=$(jobs | grep -v autojump | wc -l | sed 's/^ *//g')
  if [ $num != 0 ]; then
    echo " $num"
  fi
}

function tmux_session() {
  # if tmux on system and in a session
  if [[ $(command -v tmux) ]] && [ -n "$TMUX" ]; then
    echo "(tmux) "
  fi
}

function tmux_session_num() {
  # if tmux on system and not in a session
  if [[ $(command -v tmux) ]] && [ -z "$TMUX" ]; then
    session_num=$(tmux ls 2> /dev/null | wc -l | sed 's/^ *//g')
    if [ $session_num != 0 ]; then
      echo " $session_num"
    fi
  fi
}

# LogGrep
#
# grep yteam prod logs
#   log-grep <app> <process> <hour>
#
# Examples:
#   check capn process yt2 log through 3pm-4pm:
#     log-grep capn yt2 15
#   check datum process yt4 log for errors plus subsequent 3 lines
#     log-grep datum yt4 | grep -A 3 Errno
log-grep() {
  ssh -t david.ross@ng.ldc.yougov.local \
    "find /mnt/syslogng/yhost_procs/ . -name 'yproc-$1.log' | \
     xargs grep $2 | \
     ( [[ ! '$3' ]] && cat || grep $3':[0-9][0-9]:[0-9][0-9]' )"
}

# multiple git 'aliases'
function git() {
  if [[ $@ == 'graph' ]]; then
    command git log --graph --oneline --decorate --all
  elif [[ $@ == 'current-tag' ]]; then
    command git describe --tags --abbrev=0
  else
    command git "$@"
  fi
}

# go up x many dirs:
#    up 2 == cd ../../
function up() {
  if [[ "$#" == 0 ]]; then
    cd ..
  else
    CDSTR=""
    for i in $(seq 1 $1); do
      CDSTR="../$CDSTR"
    done
    cd $CDSTR
  fi
}

# stream torrent magnet in VLC
function vlc-stream() {
  # use CTRL+Z and then type `bg` to take back your terminal
  peerflix "$1" --remove --vlc --quiet --list
}


#################
#    OPTIONS    #
#################

export PATH=$PATH:$HOME/.npm-global/bin:$HOME/.gem/ruby/2.7.0/bin:$HOME/.cargo/bin

# VI mode
set -o vi

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# append to the history file, don't overwrite it
shopt -s histappend

# Combine multiline commands into one in history
shopt -s cmdhist

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
# shopt -s globstar

# use dircolor options
# if [ -x /usr/bin/dircolors ]; then
#   test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
#   test -r ~/.dir_colors && eval "$(dircolors -b ~/.dir_colors)" || eval "$(dircolors -b)"
# fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


#################
#    HISTORY    #
#################

# don't put duplicate lines or lines starting with space in the history.
export HISTCONTROL=ignoreboth
export HISTSIZE=100000
export HISTFILESIZE=200000
# don't show repeated commands (&), ls, ls *, etc.
export HISTIGNORE="&:history:hgrep:h:cll:cll *:cls:c:c *:ls:ls *:cd:cd *:ps:ps -A:[bf]g:fg:tmux:vim:j:exit"
MY_BASH_GREEN="\033[38;5;82m"
MY_BASH_NOCOLOR="\033[0m"
HISTTIMEFORMAT=`echo -e ${MY_BASH_GREEN}[%F %T] $MY_BASH_NOCOLOR `


#################
#    COLOURS    #
#################

# change the colour of the dirs and executable files
# NOTE: see `dircolors` cmd & ~/.dir_colors for colouring specific extensions
export LS_COLORS=$LS_COLORS:'di=38;5;165:ex=38;5;226:fi=0:ln=38;5;204:*.md=0;37:*.txt=0;37'

# Cloured Man Pages
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

# coloured less pages
export LESSOPEN="| /usr/bin/src-hilite-lesspipe.sh %s"
export LESS=' -R '


#################
#    EDITOR     #
#################

export VISUAL=vim
export EDITOR="$VISUAL"
export VIMRC=~/.vimrc


#################
#    PLUGINS    #
#################

# venv settings
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel

# source plugins
if [[ $os = 'Darwin' ]]; then
  export VIRTUALENVWRAPPER_PYTHON=/Library/Frameworks/Python.framework/Versions/3.8/bin/python3
  source /usr/local/bin/virtualenvwrapper.sh
else
  source /usr/share/fzf/completion.bash
  source /usr/share/fzf/key-bindings.bash
  source /usr/bin/virtualenvwrapper.sh
fi

[[ -s /home/${USER}/.autojump/etc/profile.d/autojump.sh ]] && source /home/${USER}/.autojump/etc/profile.d/autojump.sh
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#################
#    PROMPT     #
#################

# Red username in prompt if remote accessing a computer
# Assumes hostname on original hardware has hostname with david in it
case $(hostname -s) in
david*)
  export USER_PS1="\u"
  ;;
*)
  export USER_PS1="\[\033[1;31m\]\u@\h\[\033[00m\]"
  ;;
esac

export PS1="$USER_PS1 \w"\
"\[\033[38;5;82m\]\$(parse_git_branch)\[\033[00m\]"\
"\[\033[38;5;87m\]\$(bg_process_num)\[\033[00m\] $ "
# "\e[38;5;202m\]\$(tmux_session_num)\[\033[00m\] $ "
